server:
  port: 7000
  servlet:
    session.timeout: 300

logging:
  level:
    org.springframework.web: debug
    cn.zifangsky.easylimit: debug
  file: logs/easylimit-token-example.log


spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/easylimit?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  #redis
  redis:
      cluster:
        nodes: redis:7001,redis:7002,redis:7003
        max-redirects: 6
      timeout: 300000
      jedis:
        pool:
          max-active: 8
          max-wait: 100000
          max-idle: 8
          min-idle: 0


#mybatis
mybatis:
  type-aliases-package: cn.zifangsky.easylimit.token.example.mapper
  mapper-locations: classpath:mapper/*.xml

#是否开启Springfox Swagger
swagger.enabled: true